// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7w7O1IioyeprY7Vpwx-BcrMxdY2UJF1s',
    appId: '1:472000393996:web:1a431b12868bf0a63a4f29',
    messagingSenderId: '472000393996',
    projectId: 'build-release-a71f9',
    authDomain: 'build-release-a71f9.firebaseapp.com',
    storageBucket: 'build-release-a71f9.appspot.com',
    measurementId: 'G-K0VWG8QHFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhVCeCZzB0S5gU47XcKWcJLTmDfSxHec',
    appId: '1:472000393996:android:75bac3f5e7210e953a4f29',
    messagingSenderId: '472000393996',
    projectId: 'build-release-a71f9',
    storageBucket: 'build-release-a71f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr45wTYvVdRcL0W_yKaq-UcyHAbcaHqJY',
    appId: '1:472000393996:ios:8ab1fc5e0f450b523a4f29',
    messagingSenderId: '472000393996',
    projectId: 'build-release-a71f9',
    storageBucket: 'build-release-a71f9.appspot.com',
    iosClientId: '472000393996-1agpsbr0h9u74nmn13b5e9b1bb86knv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildCi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr45wTYvVdRcL0W_yKaq-UcyHAbcaHqJY',
    appId: '1:472000393996:ios:daa97f777a2a08433a4f29',
    messagingSenderId: '472000393996',
    projectId: 'build-release-a71f9',
    storageBucket: 'build-release-a71f9.appspot.com',
    iosClientId: '472000393996-4a2fof8gaasv2bc59alprts2dnra08sa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirius.siriusExample',
  );
}
